name: porfolio
description: "Mobile Engineer || Flutter"

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  simple_gradient_text: ^1.3.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.1
  get: ^4.6.6
  visibility_detector: ^0.4.0+2
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/json/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 900
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
